//  APIClient.h
//
//  Generated by the the JBoss AeroGear Xcode Project Template on ___DATE___.
//  See Project's web site for more details http://www.aerogear.org
//

#import "AeroGear.h"

@interface APIClient : NSObject

// the pipes for this service
@property(readonly, nonatomic) id<AGPipe> pipe;
// ...add your own pipes

+ (APIClient *)sharedInstance;

- (void)loginWithUsername:(NSString *)username
                 password:(NSString *)password
                  success:(void (^)())success
                  failure:(void (^)(NSError *error))failure;
@end